//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by HSDPA.rc
//
#define IDC_BUTTON_SIGNIN               3
#define IDC_BUTTON_SUBMIT               3
#define IDC_BUTTON_MPIN_OK              3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_HSDPA_DIALOG                102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDS_SMS                         104
#define IDS_CALL                        105
#define IDS_PHONEBOOK                   106
#define IDS_SETUP                       107
#define IDS_INTERNET                    108
#define IDS_INCALLING                   109
#define IDS_SMS_RECIEVED                110
#define IDS_SMS_RECEIVED                110
#define IDS_SMS_INBOX                   110
#define IDS_SMS_SENT                    111
#define IDS_SMS_OUTBOX                  111
#define IDS_SMS_SENDER                  112
#define IDS_NUMBER                      113
#define IDS_MOBILE                      113
#define IDS_DATETIME                    114
#define IDS_SMS_DATETIME                114
#define IDS_DETAILS                     115
#define IDS_NAME                        116
#define IDS_SMS_SENDER_NAME             117
#define IDS_SMS_CONTENT                 118
#define IDS_DATASERVICING               119
#define IDS_CALL_STATUS_CALLING         120
#define IDS_DELETECONFIRM               121
#define IDS_CLEARCONFIRM                122
#define IDS_DELALLCONFIRM               122
#define IDS_PB_ID                       123
#define IDS_HOME                        124
#define IDS_COMPANY                     125
#define IDS_EMAIL                       126
#define IDS_REMARK                      127
#define IDR_MAINFRAME                   128
#define IDS_SMS_ID                      128
#define IDS_ID                          128
#define IDB_BTN1                        129
#define IDR_MENU_TRAY                   129
#define IDI_ICON_INFO                   129
#define IDS_SMS_DRAFT                   129
#define IDD_CONNECTION_PAGE             129
#define IDI_ICON_WARNING                130
#define IDS_CALLHISTORY_IN              130
#define IDS_CALLHIST_RECEIVED           130
#define IDD_STATISTICS_PAGE             130
#define IDB_ICONS                       131
#define IDR_MENU1                       131
#define IDI_ICON_SMILE                  131
#define IDS_CALLHISTORY_OUT             131
#define IDS_CALLHIST_DIALED             131
#define IDD_STATUS_PAGE                 131
#define IDB_BTN1_HOT                    132
#define IDR_DIALOG_MENU                 132
#define IDS_CALLHIST_MISSED             132
#define IDB_PLAY                        133
#define IDD_DIALOG_CALL                 133
#define IDS_CALLHIST_DURATION           133
#define IDB_STOP                        134
#define IDS_DATACARD                    134
#define IDB_STOP_HOT                    135
#define IDS_SMS_READ                    135
#define IDB_PLAY_HOT                    136
#define IDS_SMS_NEW                     136
#define IDB_IMAGE                       137
#define IDS_SMS_REPLY                   137
#define IDB_TEST_BITMAP                 138
#define IDS_SMS_EDIT                    138
#define IDR_TRAYMENUIMAGES              139
#define IDS_SMS_FORWARD                 139
#define IDB_LAMPON                      140
#define IDS_SMS_DELETE                  140
#define IDR_TOOLBAR_MENU_IMAGES         141
#define IDS_SMS_DELALL                  141
#define IDD_DIALOG_SMS                  142
#define IDS_SMS_DIAL                    142
#define IDD_DIALOG_PHONEBOOK            143
#define IDS_SMS_ABSTRACT                143
#define IDB_CHECK                       144
#define IDD_DIALOG_SETUP                144
#define IDS_WARNING_INPUTNUM            144
#define IDD_TABDLG_MAIN                 145
#define IDS_WARNING_INPUTSMS            145
#define IDB_RADIO_ON                    146
#define IDD_DIALOG_TEST                 146
#define IDS_SMS_SAVESUCC                146
#define IDD_DIALOG_INTERNET             147
#define IDS_SMS_SAVEFAIL                147
#define IDB_LAMPOFF                     148
#define IDD_DIALOG_CALL_HISTORY         148
#define IDS_UNKNOWN                     148
#define IDD_DIALOG_CALLDIAL             149
#define IDS_SMS_IMPORT                  149
#define IDS_SMS_TRANSFER                149
#define IDB_LOGO                        150
#define IDS_SMS_EXPORT                  150
#define IDB_CHECKNO                     151
#define IDS_NOITEMSEL                   151
#define IDB_GLOBE                       152
#define IDS_CALLHIST_FREQUENCY          152
#define IDB_RADIO_OFF                   153
#define IDS_HELPDOC                     153
#define IDB_TABICONS_CALLHISTORY        154
#define IDS_HELPINFO                    154
#define IDS_LOG_NTYPE                   155
#define IDS_LOG_TIMESTAMP               156
#define IDS_LOG_DURATION                157
#define IDD_DIALOG_WRITESMS             158
#define IDS_LOG_BYTEIN                  158
#define IDD_DIALOG_CONTACT              159
#define IDS_LOG_BYTEOUT                 159
#define IDD_DIALOG_DATASERVICEHISTORY   160
#define IDS_SMS_STATE_SENT              160
#define IDS_SMS_STATE_NOT_READ          161
#define IDD_PROFILE_UMTS_REQ_PAGE       161
#define IDS_SMS_STATE_READ              162
#define IDD_PROFILE_UMTS_MIN_PAGE       162
#define IDS_SMS_STATE_NOT_SENT          163
#define IDD_PROFILE_GPRS_REQ_PAGE       163
#define IDS_FILE_EXIST                  164
#define IDD_PROFILE_GPRS_MIN_PAGE       164
#define IDS_USB_NOTFIND                 165
#define IDD_SIM_PAGE                    165
#define IDS_USB_START_SUCC              166
#define IDD_testDIALOG                  167
#define IDS_USB_START_FAIL              167
#define IDS_USB_PORT_WAIT               168
#define IDS_USB_PORT_INI                169
#define IDS_USB_PORT_EXCEPTION          170
#define IDD_DIALOG_PINCLCK              171
#define IDS_USB_PORT_TIMEOUT            171
#define IDD_DIALOG_MODIFY_PIN           172
#define IDS_USB_PORT_DATA               172
#define IDI_ICON1                       173
#define IDS_USB_PORT_CALL               173
#define IDD_TestTip                     174
#define IDS_PC                          174
#define IDD_DIALOG_READSMS              175
#define IDS_USIM                        175
#define IDS_ME                          176
#define IDS_SMS_FULL                    177
#define IDD_DIALOG_SELCONTACT           178
#define IDS_USB_PORT_DISC               178
#define IDD_DIALOG_PRE_TIP              179
#define IDS_UNKNOWN_NAME                179
#define IDB_SPLASH                      180
#define IDS_SMS_SEND_SUCC               180
#define IDR_MENU2                       181
#define IDR_MENU_HIST_RCLICK            181
#define IDS_SMS_SEND_FAIL               181
#define IDD_DIALOG_SEARCH               182
#define IDS_PBMENU_ADDPB                182
#define IDD_DIALOG_TRANSFER             183
#define IDS_PBMENU_DELETE               183
#define IDD_DIALOG_SELPOSITION          184
#define IDS_PBMENU_MODIFY               184
#define IDD_DIALOG_CALL_LOG             185
#define IDS_PBMENU_DELETEALL            185
#define IDB_DOWN                        186
#define IDS_PBMENU_CALL                 186
#define IDR_MENU_LOG_RCLICK             187
#define IDS_PB_SENDSMS                  187
#define IDS_PBMENU_SEARCHPB             188
#define IDD_DIALOG_POP_TIP              189
#define IDS_PBMENU_TRANSFER             189
#define IDD_DIALOG_SENDSMS              190
#define IDS_PBMENU_IMPORTPB             190
#define IDD_DIALOG_SEL_DIAL             191
#define IDS_PBMENU_EXPORTPB             191
#define IDD_DIALOG_PBSELPOSITION        192
#define IDS_PB_SAVE                     192
#define IDS_PB_SAVEFAILED               192
#define IDD_DIALOG_TRANSMS              193
#define IDS_SMS_NULL                    193
#define IDI_ICON_SET                    194
#define IDS_PB_FULL                     194
#define IDI_ICON_SET_HV                 195
#define IDS_PB_IMPORTTIP                195
#define IDI_ICON_NET                    196
#define IDS_PBTRANSFER_FAILED           196
#define IDI_ICON_CALL_HV                197
#define IDS_PBTRANSFER_CARDCOLUMN       197
#define IDI_ICON_CALL                   198
#define IDS_TIPINFO_SMS                 198
#define IDI_ICON_SMS_HV                 199
#define IDS_SELCONNECT_NULLNUM          199
#define IDI_ICON_SMS                    200
#define IDS_MENU_LANGUAGE_ENG           200
#define IDS_MENU_LANGUAGE               200
#define IDI_ICON_PHBK_HV                201
#define IDS_MENU_LANGUAGE1              201
#define IDS_LANG_ENG                    201
#define IDI_ICON_PHBK                   202
#define IDS_PBTRANSFER_INITCARDINFO     202
#define IDI_ICON_NET_HV                 203
#define IDS_PBTRANSFER_INITUSIMINFO     203
#define IDS_UIM                         204
#define IDS_PBTRANSFER_CARDFULL         204
#define IDB_BACK_PAGE1                  205
#define IDS_PBTRANSFER_USIMFULL         205
#define IDB_BACK_CON                    206
#define IDS_TIPINFO_CALL                206
#define IDD_DIALOG_PROGRESS             207
#define IDS_MENU_LANGUAGE2              207
#define IDS_LANG_ITA                    207
#define IDB_BACK_SCREEN                 208
#define IDS_PB_ADDPICERR                208
#define IDD_DIALOG_WAITING              209
#define IDS_PB_NAMELENMAX               209
#define IDB_SMS_STATE                   210
#define IDS_PB_DELPCERR                 210
#define IDB_SMS_TYPE                    211
#define IDS_PB_DELPCCARDERR             211
#define IDI_ICON_XSMS                   212
#define IDS_TRAY_TOTRAY                 212
#define IDS_TRAY_OPENDLG                213
#define IDD_DIALOG_SETUP_SKIN           214
#define IDS_CARD_DISCONN                214
#define IDD_DIALOG_SETUP_SECURITY       215
#define IDS_RF_SETERROR                 215
#define IDD_DIALOG_SETUP_GENERAL        216
#define IDS_INTERNET_TOOMANYENTRY       216
#define IDI_ICON_PADHANGUP              217
#define IDS_ERROR_NOT_ENOUGH_MEMORY     217
#define IDI_ICON_PADCALL                218
#define IDS_ERR_SMS_GROUPNUMBEROVER     218
#define IDD_DIALOG_PROGRESSEX           219
#define IDS_SMS_ME_FULL                 219
#define IDD_DIALOG_INTERNET_NEWCONN     220
#define IDS_SMS_USIM_FULL               220
#define IDD_DIALOG_SMS_EXPORT           221
#define IDS_SMS_MEUSIM_FULL             221
#define IDS_INT_ERR_INPUTNULL           222
#define IDS_INT_ERR_SAMENAME            223
#define IDS_INT_ERR_INPUTLONG           224
#define IDS_CALL_ERR_CALLFAIL           225
#define IDB_PBTRANSFER_UP               226
#define IDS_QUIT_TIP                    226
#define IDS_QUIT_INTERNET               227
#define IDB_PBTRANSFER_DOWN             228
#define IDS_INT_ERR_DELACTCON           228
#define IDB_ICON_RSSI0                  229
#define IDS_SETUP_CONNPOINTERROR        229
#define IDB_ICON_RSSI1                  230
#define IDS_SETUP_CONNPOINTOK           230
#define IDB_ICON_RSSI2                  231
#define IDS_READ_SMS_DATA               231
#define IDB_ICON_RSSI3                  232
#define IDS_READ_PBM_DATA               232
#define IDB_ICON_RSSI4                  233
#define IDS_READ_CALL_DATA              233
#define IDB_ICON_RSSI5                  234
#define IDS_READ_NW_DATA                234
#define IDB_ICON_SMS_UNRD               235
#define IDS_CHECK_SIM_STATUS            235
#define IDD_DIALOG_SETUP_MESSAGES       236
#define IDS_CHECK_SMS_STATUS            236
#define IDD_DIALOG_SIGNIN               237
#define IDS_CHECK_PBM_STATUS            237
#define IDB_ICON_SMS_FULL               238
#define IDS_CHECK_DATACARD_STATUS       238
#define IDS_TIMEOUT_SIM_INIT            239
#define IDB_ICON_NWT_GSM                240
#define IDS_TIMEOUT_SMS_INIT            240
#define IDB_ICON_NWT_WCDMA              241
#define IDS_TIMEOUT_PBM_INIT            241
#define IDB_ICON_NULL                   242
#define IDS_CHECK_HANDSET_STATUS        242
#define IDD_DIALOG_MSGBOX               243
#define IDS_CHECK_RFPOWER_STATUS        243
#define IDB_BACK_SLIDER                 244
#define IDS_READ_PLMN_DATA              244
#define IDB_BACK_SLIDERTIC              245
#define IDS_READ_NWTYPE_DATA            245
#define IDB_ICON_HANDSET_ON             246
#define IDS_CHECK_ROAM_STATUS           246
#define IDB_ICON_HANDSET_OFF            247
#define IDS_READ_RSSI_DATA              247
#define IDD_DIALOG_SEL_NUMBER           248
#define IDS_CONFIG_SMS_MODE             248
#define IDB_ICON_NWT_EDGE               249
#define IDS_CONFIG_SMS_ROUTE            249
#define IDB_ICON_NWT_GPRS               250
#define IDS_READ_SMS_STORAGE            250
#define IDB_ICON_NWT_HSDPA              251
#define IDS_CONFIG_INCOMING_CALL        251
#define IDB_CALL_STATE                  252
#define IDS_CONFIG_CHSET                252
#define IDB_ICON_ROAM_FLASH             253
#define IDS_CONFIG                      253
#define IDB_ICON_ROAM_ON                254
#define IDS_TIMEOUT_HANDSET_INIT        254
#define IDS_TIMEOUT_RF_POWER_INIT       255
#define IDB_ICON_LONGNULL               256
#define IDS_TIMEOUT_PLMN_INIT           256
#define IDD_DIALOG_SETUP_NWSEL          257
#define IDS_TIMEOUT_NWTYPE_INIT         257
#define IDS_TIMEOUT_ROAM_INIT           258
#define IDD_DIALOG_VERSION              258
#define IDS_TIMEOUT_RSSI_INIT           259
#define IDD_DIALOG_LANGUAGE             259
#define IDS_TIMEOUT_SMSMODE_INIT        260
#define IDR_WAVE_CALL                   260
#define IDS_TIMEOUT_SMSROUTE_INIT       261
#define IDR_WAVE_SMS                    261
#define IDS_TIMEOUT_SMSSTORAGE_INIT     262
#define IDS_TIMEOUT_INCOMCALL_INIT      263
#define IDS_TIMEOUT_CHSET_INIT          264
#define IDS_TIMEOUT_CONFIG_INIT         265
#define IDS_PB_SELNULL                  266
#define IDS_PB_SMSSELMAX                267
#define IDS_PB_SAVEERR                  268
#define IDS_PB_ADDPBFAIL                269
#define IDS_PB_UPDATAERR                270
#define IDS_PB_DELERR                   271
#define IDS_APPNAME                     272
#define IDS_PB_NULLPB                   273
#define IDS_PB_READERR                  274
#define IDS_FILEERR                     275
#define IDS_PB_INPORTERR                276
#define IDD_DIALOG_MESSAGE              276
#define IDS_PB_NAMEMAX                  277
#define IDD_DIALOG_RESDLLNOTFOUND       277
#define IDS_CONFIG_CGMR                 278
#define IDS_PB_IMPORTFILEERR            279
#define IDS_CALL_SIMSTATEWRONG          280
#define IDS_CONTACT_NAMETOOLONG         281
#define IDS_CONTACT_NOPLUSONLY          282
#define IDS_INTERNET_RASENUMERROR       283
#define IDS_PIN_PROTIP                  284
#define IDD_DIALOG_HOOK                 284
#define IDS_PIN_LOCK                    285
#define IDS_PIN_MODIFY                  286
#define IDI_ICON_HELP_HV                286
#define IDI_ICON_HELP                   287
#define IDS_PUK_LOCK                    287
#define IDS_PIN_ENABLE_T                288
#define IDS_PIN_DISABLE_T               289
#define IDS_PIN_ERR_LEN                 290
#define IDD_DIALOG_SMS_EXTRACTNUM       290
#define IDS_PIN_WR_ENABLE               291
#define IDI_ICON_BROWSE                 291
#define IDD_DIALOG_PBIMPORT             291
#define IDI_ICON_BROWSE_HV              292
#define IDS_PIN_WR_DISABLE              292
#define IDD_DIALOG_PBGETOUTLOOK         292
#define IDS_PIN_ERR_PIN1                293
#define IDI_ICON_USSD_HV                293
#define IDS_PIN_MODIFY_T                294
#define IDB_BACK_MAIN_DEFAULT           294
#define IDI_ICON_USSD                   294
#define IDS_PIN_UNLOCK_T                295
#define IDB_BACK_CON_DEFAULT            295
#define IDD_DIALOG_SETUP_PREFER         295
#define IDC_CURSOR1                     295
#define IDS_PIN_BTNT                    296
#define IDS_PUK_BTNT                    297
#define IDB_PB_LOCSTATE                 297
#define IDS_PIN_ERR_UNSAME              298
#define IDD_DIALOG_DIAGNOSTICS          298
#define IDS_PUK_ERR                     299
#define IDD_DIALOG_INTERNET_USAGELIMIT  299
#define IDS_SIM_DESTROYED               300
#define IDD_DIALOG_INTERNET_TIP         300
#define IDB_BITMAP_VOLUME               300
#define IDS_PIN_MODIFY_OK               301
#define IDD_DIALOG_INTERNET_PWDCONFIRM  301
#define IDS_INT_ERR_INPUTERROR          302
#define IDD_DIALOG_INTERNET_PWDMODIFY   302
#define IDD_DIALOG_USSD_SERVICE         303
#define IDS_INT_ERR_INPUTTOOLONG        303
#define IDB_BACK_MAIN                   304
#define IDS_INT_ERR_NOUSB               304
#define IDD_DIALOG_INTERNET_FORNDISSWITCH 304
#define IDS_INT_ERR_DELETERASERROR      305
#define IDB_BITMAP_VIVO                 305
#define IDD_CONNECTIONMANAGER_DIALOG    305
#define IDS_INT_ERR_RASERRORFORMAT      306
#define IDB_BITMAP_AMAZONIA             306
#define IDD_PROFILE_GENERAL_PAGE        306
#define IDS_INT_CONNECTED               307
#define IDB_BITMAP_CLARO                307
#define IDD_PROFILES_PAGE               307
#define IDS_INT_CONNLIMITEFORMAT        308
#define IDB_BITMAP_TELEMIG              308
#define IDS_CONTACT_PLUS                309
#define IDB_BITMAP_OI                   309
#define IDS_PB_NULLDEL                  310
#define IDB_ICON_UE_PS                  310
#define IDS_MODIFYPIN_DISABLE           311
#define IDB_ICON_NWT_HSUPA              311
#define IDS_SIGNIN_NEEDPUK              312
#define IDS_GENERATOR_CREATEFAIL        313
#define IDS_GENERATOR_FILENAMEERR       314
#define IDS_GENERATOR_LESSMEM           315
#define IDD_DIALOG_NET_STATISTICS       315
#define IDS_GENERATOR_CSVADNVCF         316
#define IDD_DIALOG_PBGROUP              316
#define IDS_GENERATOR_CSVEX             317
#define IDD_DIALOG_CONNECT              317
#define IDS_GENERATOR_VCFEX             318
#define IDD_DIALOG_PBGROUP_NEW          318
#define IDD_DIALOG_GPMEMBER             319
#define IDS_GENERATOR_CSV               319
#define IDS_GENERATOR_TITLE             320
#define IDD_DIALOG_PROFILE              320
#define IDS_GENERATOR_CSVTITLE          321
#define IDS_PARSER_LOADFILE             322
#define IDS_NO_NEWSMS                   323
#define IDD_DIALOG1                     323
#define IDS_POP_SMS_T                   324
#define IDS_POP_CALL_T                  325
#define IDS_SMS_SENDING_TIP             326
#define IDS_APPPRONAME                  327
#define IDI_ICON_TRANSFER               327
#define IDI_ICON_UPLOAD                 328
#define IDS_ABOUTURL                    328
#define IDS_ABOUTEMAIL                  329
#define IDS_APPSKINPASH                 330
#define IDS_APPXPSKINPATH               331
#define IDI_ICON_NODE                   331
#define IDS_INT_CONNSTS_CONNECTING      332
#define IDS_INT_CONNSTS_DEVCONNECTED    333
#define IDS_INT_CONNSTS_AUTHENTICATING  334
#define IDI_ICON_DAILY                  334
#define IDS_INT_CONNSTS_AUTHENTICATED   335
#define IDI_ICON_MONTHLY                335
#define IDS_INT_CONNSTS_CONNECTED       336
#define IDI_ICON_YEARLY                 336
#define IDS_INT_CONNSTS_DISCONNECTED    337
#define IDS_SET_TAB_GENERAL             338
#define IDI_ICON_DOWNLOAD               338
#define IDS_SET_TAB_SECURITY            339
#define IDS_SET_TAB_MESSAGES            340
#define IDI_ICON_USSDDOWN               340
#define IDS_SET_TAB_NETWORK             341
#define IDI_ICON_USSDNORMAL             341
#define IDS_INT_NUMBERCHANGE            342
#define IDI_ICON_STATISTICS             342
#define IDD_DIALOG_PROFILE_CDMA2000     342
#define IDS_MAIN_CGMRERROR              343
#define IDD_DIALOG_PROFILE_NEWCDMA2000  343
#define IDI_ICON_SMS_FILE               343
#define IDS_MAIN_CGSNERROR              344
#define IDI_ICON3                       344
#define IDD_DIALOG_NETWORKSETTING_CDMA  344
#define IDB_BITMAP_STATUSICONBK         344
#define IDI_ICON_SMS_INBOX              344
#define IDS_CONFIG_CGSN                 345
#define IDB_ICON_LONGNULL_SPEED         345
#define IDI_ICON_SMS_OUTBOX             345
#define IDS_TIMEOUT_CGMR_INIT           346
#define IDI_ICON_SMS_DRAFT              346
#define IDS_TIMEOUT_CGSN_INIT           347
#define IDI_ICON_SMS_ARCHIVE            347
#define IDI_ICON_USSDPRESS              347
#define IDS_CONFIG_SMS_CSDH             348
#define IDI_ICON_USAGE_HV               348
#define IDS_TIMEOUT_SMSCSDH_INIT        349
#define IDS_INT_CONN_SIMNOTREADY        350
#define IDI_ICON_SMS_EDIT               350
#define IDS_ABOUT_COPYRIGHT             351
#define IDI_ICON_SMS_PRESS              351
#define IDS_IMEI                        352
#define IDI_ICON_NET_PRESS              352
#define IDS_FIRMWARE_VERSION            353
#define IDI_ICON_BROWSE_PRESS           353
#define IDS_SOFTWARE_VERSION            354
#define IDI_ICON_USAGE_PRESS            354
#define IDS_CONNTYPE_UNKNOW             355
#define IDI_ICON_CALL_PRESS             355
#define IDS_CONNTYPE_GPRS               356
#define IDI_ICON_PHONEBOOK_PRESS        356
#define IDS_CONNTYPE_EDGE               357
#define IDI_ICON_SETUP_PRESS            357
#define IDS_CONNTYPE_HSDPA              358
#define IDI_ICON_SMSNEW                 358
#define IDS_SETUP_SCA_ERROR             359
#define IDI_ICON_SMSREPLY               359
#define IDS_START_INSERTPCCARD          360
#define IDI_ICON_SMSFORWARD             360
#define IDS_SETUP_SCA_OK                361
#define IDI_ICON_SMSDELEDT              361
#define IDS_SETUP_COPS_ERROR            362
#define IDI_ICON_SMSEXTRACT             362
#define IDS_SMS_MOVE_TIP                363
#define IDI_ICON_SMSSEARCH              363
#define IDS_SETUP_COPS_SETERROR         364
#define IDI_ICON_SMSDAIL                364
#define IDS_NWLIST_STAT                 365
#define IDB_BITMAP_SMSMENU              365
#define IDI_ICON_PB_SMS                 365
#define IDS_NWLIST_NAME                 366
#define IDI_ICON_PB_TRANSFER            366
#define IDS_NWLIST_NUMBER               367
#define IDI_ICON_PB_GROUP               367
#define IDS_NWLIST_ACT                  368
#define IDI_ICON_SMS_RESUME             368
#define IDS_NWACT_GSM                   369
#define IDS_NWACT_GSMCOM                370
#define IDS_NWACT_UTRAN                 371
#define IDS_NWSTAT_UNKNOWN              372
#define IDS_NWSTAT_AVAILABLE            373
#define IDD_DIALOG_SUBVERSION           373
#define IDI_ICON_CALL_NUM001            373
#define IDI_ICON_VOICEMAIL              374
#define IDS_NWSTAT_CURRENT              374
#define IDI_ICON_CALL_NUM01             374
#define IDS_NWSTAT_FORBIDDEN            375
#define IDI_ICON_CALL_NUM002            375
#define IDS_SETUP_NWAUTOSETERROR        376
#define IDI_ICON_CALL_NUM02             376
#define IDS_RES_DLLNOTFOUND             377
#define IDI_ICON_CALL_NUM003            377
#define IDS_SETUP_CGDCONT_ERROR         378
#define IDI_ICON_CALL_NUM03             378
#define IDS_DATACARD_NOT_INSERT         379
#define IDI_ICON_CALL_NUM004            379
#define IDS_SIM_NOT_INSERT              380
#define IDD_DIALOG_COPS_TIP             380
#define IDI_ICON_CALL_NUM04             380
#define IDS_CONTACT_A                   381
#define IDI_ICON_CALL_NUM005            381
#define IDS_REFRESH_NWLIST              382
#define IDI_ICON_CALL_NUM05             382
#define IDS_CONTACT_ERRMAIL             383
#define IDI_ICON_CALL_NUM006            383
#define IDS_SETOK                       384
#define IDI_ICON_CALL_NUM06             384
#define IDS_SMS_READ_REPLAY             385
#define IDI_ICON_CALL_NUM007            385
#define IDS_SMS_READ_EXIT               386
#define IDI_ICON_CALL_NUM07             386
#define IDS_NW_SRV_NO                   387
#define IDI_ICON_CALL_NUM008            387
#define IDS_NW_SRV_LIMIT                388
#define IDI_ICON_CALL_NUM08             388
#define IDS_INT_DELPROFILE              389
#define IDI_ICON_CALL_NUM009            389
#define IDS_SET_TAB_SKIN                390
#define IDI_ICON_CALL_NUM09             390
#define IDS_NOSMSITEMSEL                391
#define IDI_ICON_CALL_NUM000            391
#define IDS_SMS_PCCARD_FULL             392
#define IDI_ICON_CALL_NUM00             392
#define IDS_INIT_SEARCH_DEVICE          393
#define IDI_ICON_CALL_NUMHASH001        393
#define IDS_SET_TAB_PROFILES            394
#define IDI_ICON_CALL_NUMHASH01         394
#define IDS_SET_TAB_PREFER              395
#define IDI_ICON_CALL_NUMSTAR001        395
#define IDS_SAVEOK                      396
#define IDI_ICON_CALL_NUMSTAR01         396
#define IDS_CHOOSE_SOUNDFILE            397
#define IDI_ICON_CALL_NUMCONTACTS001    397
#define IDS_INT_NOPROFILE               398
#define IDI_ICON_CALL_NUMCONTACTS01     398
#define IDS_INT_DISC_TIP                399
#define IDI_ICON_CALL_NUMCLEAR001       399
#define IDS_SAVETIP                     400
#define IDI_ICON_CALL_NUMCLEAR01        400
#define IDS_INT_LIMIT_FLUX              401
#define IDI_ICON_CALL_NUMCALL001        401
#define IDS_INT_LIMIT_DURATION          402
#define IDI_ICON_CALL_NUMCALL01         402
#define IDS_INT_APN_EMPTY               403
#define IDI_ICON_CALL_NUMEND001         403
#define IDS_INT_BUTTON_CONN             404
#define IDI_ICON_CALL_NUMEND01          404
#define IDS_INT_BUTTON_DISC             405
#define IDS_EXPORT_PBHEADER             406
#define IDB_BITMAP_UPSPEEDICON          406
#define IDS_EXPORT_SMSHEADER            407
#define IDB_BITMAP_DOWNSPEEDICON        407
#define IDS_EXPORT_NETHEADER            408
#define IDS_SEARCH_NWLIST               409
#define IDS_PB_DELUSIMERR               410
#define IDS_PB_DELPCCARD_WAITINFO       411
#define IDS_PB_DELUSIM_WAITINFO         412
#define IDS_SCA_TIP                     413
#define IDS_INTERNET_PWDERR             414
#define IDS_INTERNET_PWDDIFF            415
#define IDS_INTERNET_MODIFYPWDSUCC      416
#define IDS_SIMLOCK                     417
#define IDS_INTERNET_REACHLIMIT         418
#define IDS_NOTOUTLOOK                  419
#define IDS_PC_SMS_FULL                 420
#define IDS_INTERNET_DELERR             421
#define IDS_INTERNET_EDITERR            422
#define IDS_SETUP_COPS_SETSUCC          423
#define IDS_USER_GUIDE                  424
#define IDS_NETCARD_NOT_FOUND           425
#define IDS_WAIT_READ_SMS               426
#define IDS_WAIT_DELETE_SMS             427
#define IDS_WAIT_TRANSFER_SMS           428
#define IDS_PBGROUP                     429
#define IDS_GROUP_FULL                  430
#define IDS_NETTREE_EXPANDALL           432
#define IDS_NETTREE_COLLAPSEALL         433
#define IDS_SMS_SEARCHCONDITION         434
#define IDS_NETTREE_RESETSTATISTICS     435
#define IDS_WARNING_RESETSTATISTICS     436
#define IDS_TIME_LASTRESET              437
#define IDS_PBMENU_GROUP                438
#define IDC_MAIL                        1000
#define IDC_URL                         1001
#define IDC_W                           1001
#define IDC_SWVERSION                   1002
#define IDC_H                           1002
#define IDC_FWVERSION                   1003
#define IDC_PIC                         1003
#define IDC_IMEI                        1004
#define IDC_BUTTON_SMS                  1005
#define IDC_STATIC_DLGCONTAINER         1007
#define IDC_BUTTON_CALL                 1008
#define IDC_EDIT1                       1008
#define IDC_EDIT_MPIN_CURR              1008
#define IDC_EDIT_SETUP_CONNPOINT        1008
#define IDC_EDIT_APN                    1008
#define IDC_EDIT_PREFER_SMSSOUND_FILE   1008
#define IDC_DATETIMEPICKER_USAGE        1008
#define IDC_EDIT_PWDCONFIRM             1008
#define IDC_EDIT_ANSWER                 1008
#define IDC_EDIT_MPWD_CURR              1008
#define IDC_EDIT_FOLDER                 1008
#define IDC_EDIT_GROUPNAME              1008
#define IDC_EDIT_SMSCONTENT             1008
#define IDC_EDI_VOICEMAILNUMBER         1008
#define IDC_BUTTON_PHONEBOOK            1009
#define IDC_EDIT3                       1009
#define IDC_EDIT_MPIN_NEW               1009
#define IDC_EDIT_INT_USAGE_DURA_H       1009
#define IDC_EDIT_MPWD_NEW               1009
#define IDC_OVERRIDE_GROUP              1009
#define IDC_BUTTON_SETUP                1010
#define IDC_EDIT4                       1010
#define IDC_EDIT_MPIN_CONF              1010
#define IDC_EDIT_INT_USAGE_DURA_M       1010
#define IDC_EDIT_MPWD_CONF              1010
#define IDC_BUTTON_CALL2                1010
#define IDC_BUTTON_HELP                 1011
#define IDC_CHECK1                      1012
#define IDC_CHECK_SET                   1012
#define IDC_CHECK_INTERNET_NEWCONN_SETDFT 1012
#define IDC_CHECK_SETDEFAULT            1012
#define IDC_BUTTON_USSD                 1012
#define IDC_BUTTON_INTERNET             1013
#define IDC_CHECK_MOVEDLG               1013
#define IDC_BUTTON_DIAL                 1014
#define IDC_BUTTON_CALLHISTORY          1015
#define IDC_BUTTON_NEWSMS               1015
#define IDC_BUTTON_NEWCONNECTION        1015
#define IDC_BUTTON_NEWCONN              1015
#define IDC_TAB_CALLHISTORY             1017
#define IDC_LIST_CALLHISTORY            1018
#define IDC_BUTTON_REPLY                1019
#define IDC_BUTTON_SENDSMS              1020
#define IDC_EDIT_NUMBER                 1020
#define IDC_BUTTON_DELALL               1020
#define IDC_BUTTON_DELETE               1021
#define IDC_BUTTON_NUM_1                1021
#define IDC_EDIT_NUMBER2                1021
#define IDC_EDIT_DURATION               1021
#define IDC_EDIT_NUMBER3                1022
#define IDC_BUTTON_READ                 1022
#define IDC_EDIT_RECEIVED               1022
#define IDC_BUTTON_EXPORT               1022
#define IDC_STATIC_STATUS               1023
#define IDC_EDIT_NUMBER4                1023
#define IDC_EDIT_SPEED                  1023
#define IDC_EDIT_NUMBER5                1024
#define IDC_EDIT_SENT                   1024
#define IDC_SLIDER_VOLUME               1025
#define IDC_APN_NAME_CHECK              1026
#define IDC_EDIT_USER                   1027
#define IDC_EDIT_USER_NAME              1027
#define IDC_EDIT_PASSWORD               1028
#define IDC_EVENTS_STATIC               1028
#define IDC_STATIC_SEND                 1029
#define IDC_EVENTS_RICHEDIT             1029
#define IDC_STATIC_RECIEVE              1030
#define IDC_STATIC_SEND2                1030
#define IDC_SELECT_DEVICE_STATIC        1030
#define IDC_STATIC_DURATIVETIME         1031
#define IDC_DEVICE_NAME_COMBO           1031
#define IDC_BUTTON_DETAILS              1032
#define IDC_CONNECT_BUTTON              1032
#define IDC_BUTTON_NUM_2                1033
#define IDC_BATTERY_STATIC              1033
#define IDC_BUTTON_NUM_3                1034
#define IDC_BUTTON_DISCONNECT           1034
#define IDC_LIST_PHONEBOOK              1034
#define IDC_BATTERY_PROGRESS            1034
#define IDC_BUTTON_NUM_4                1035
#define IDC_BUTTON_ADD                  1035
#define IDC_SIGNAL_STATIC               1035
#define IDC_BUTTON_NUM_5                1036
#define IDC_STATIC_RECEIVED_CAPTION     1036
#define IDC_SIGNAL_PROGRESS             1036
#define IDC_TX_GROUP                    1036
#define IDC_BUTTON_NUM_6                1037
#define IDC_RX_GROUP                    1037
#define IDC_BUTTON_NUM_7                1038
#define IDC_TX_RATE_STATIC              1038
#define IDC_BUTTON_NUM_8                1039
#define IDC_BUTTON_NUM_9                1040
#define IDC_RX_RATE_STATIC              1040
#define IDC_BUTTON_NUM_STAR             1041
#define IDC_BUTTON_NUM_0                1042
#define IDC_TX_PACKETS_OK_STATIC        1042
#define IDC_BUTTON_NUM_HASH             1043
#define IDC_TX_PACKET_ERRS_STATIC       1043
#define IDC_BUTTON_HUNGUP               1044
#define IDC_RX_PACKETS_OK_STATIC        1044
#define IDC_LIST_SMS                    1045
#define IDC_TX_OVERFLOWS_STATIC         1045
#define IDC_RX_PACKET_ERRS_STATIC       1046
#define IDC_RX_OVERFLOWS_STATIC         1047
#define IDC_BUTTON_FORWARD              1048
#define IDC_MAX_TX_RATE_STATIC          1048
#define IDC_MAX_RX_RATE_STATIC          1049
#define IDC_MFR_STATIC                  1050
#define IDC_REV_ID_STATIC               1051
#define IDC_ISDN_STATIC                 1052
#define IDC_MODEL_ID_STATIC             1053
#define IDC_STATIC_NUMBEROFWORDS        1054
#define IDC_SERIAL_NUMBER_STATIC        1054
#define IDC_SIM_STATIC                  1055
#define IDC_DEVICE_INFORMATION_GROUP    1056
#define IDC_EDIT_SMSDETAILS             1057
#define IDC_EDIT_NAME                   1058
#define IDC_LIST_HISTORY                1059
#define IDC_COMBO1                      1060
#define IDC_COMBO_CONNECT_NAME          1060
#define IDC_COMBO_SELNUM                1060
#define IDC_COMBO_SEND                  1060
#define IDC_BUTTON_ABSTRACT             1061
#define IDC_COMBO_SELUP                 1061
#define IDC_TECH_PREF_CHECK             1061
#define IDC_BUTTON_ENABLEPIN            1062
#define IDC_TECH_PREF_COMBO             1062
#define IDC_BUTTON_DISABLE_PIN          1063
#define IDC_AUTH_PREF_CHECK             1063
#define IDC_EDIT2                       1064
#define IDC_EDIT_SETUP_SCA              1064
#define IDC_EDIT_INT_USAGE_FLUX         1064
#define IDC_AUTH_PREF_COMBO             1064
#define IDC_USERNAME_CHECK              1065
#define IDC_PASSWORD_CHECK              1066
#define IDC_BUTTON_DELETEALL            1067
#define IDC_EXT_POWER_STATIC            1067
#define IDC_BUTTON_SMS_READ             1068
#define IDC_BUTTON_SMS_NEW              1069
#define IDC_EDIT_SMS_NAME               1069
#define IDC_MISC_GROUP                  1069
#define IDC_BUTTON_SMS_REPLY            1070
#define IDC_DATA_BEARER_TECH_STATIC     1070
#define IDC_BUTTON_SMS_EDIT             1071
#define IDC_MAX_TX_RATE_CAP_STATIC      1071
#define IDC_BUTTON_SMS_FORWARD          1072
#define IDC_MAX_RX_RATE_CAP_STATIC      1072
#define IDC_BUTTON_SMS_DIAL             1073
#define IDC_EDIT_SMS_CONTENT            1073
#define IDC_PRIMARY_DNS_CHECK           1073
#define IDC_BUTTON_SMS_ABSTRACT         1074
#define IDC_LIST_SELCONTACT             1074
#define IDC_SECONDARY_DNS_CHECK         1074
#define IDC_BUTTON_SMS_DELETE           1075
#define IDC_BUTTON_SMS_DELALL           1076
#define IDC_PRIMARY_NBNS_CHECK          1076
#define ID_BUTTON_SMS_SEND              1077
#define IDC_BUTTON_SMS_TRANSFER         1077
#define IDC_SECONDARY_NBNS_CHECK        1077
#define ID_BUTTON_SMS_SAVE              1078
#define IDC_BUTTON_SMS_EXPORT           1078
#define IDC_STATIC_STATISTIC            1079
#define IDC_STATIC_SPLASH               1079
#define IDC_STATIC_SKIN                 1080
#define IDC_IP_ADDR_CHECK               1080
#define IDC_STATIC_PIN                  1081
#define IDC_RADIO_DEFAULT               1082
#define IDC_RADIO_XP                    1083
#define IDC_STATIC_DEFAULT              1084
#define IDC_STATIC_XP                   1085
#define IDC_IP_ADDR_IPADDRESS           1085
#define IDC_BUTTON1                     1086
#define IDC_BUTTON_INSERT               1086
#define IDC_BUTTON_FIRST                1086
#define IDC_BUTTON_CALLLOG              1086
#define IDC_BUTTON_COPY_SOME            1086
#define IDC_BUTTON_ANSWER               1086
#define IDC_BUTTON_LR                   1086
#define IDC_BUTTON_SETUP_SKIN_BROWSESKINFILE 1086
#define IDC_BUTTON_SETUP_GENERAL_SETDEFAULT 1086
#define IDC_BUTTON_TRANSFER             1086
#define IDC_BUTTON_SETUP_POWERMNG_POWERONOFF 1086
#define IDC_BUTTON_SETUP_POWERMNG_POWERON 1086
#define IDC_BUTTON_SETUP_NWSEL_AUTOSEL  1086
#define IDC_BUTTON_SETUP_NWSEL_REFRESH  1086
#define IDC_LOADPIC                     1086
#define IDC_BUTTON_SETUP_MSGSET         1086
#define IDC_BUTTON_HOMEPAGE             1086
#define IDC_BUTTON_BROWSE               1086
#define IDC_BUTTON_PREFER_SMSSOUND_BROWSE 1086
#define IDC_BUTTON_MODIFYPWD            1086
#define IDC_3GPP_PROFILE_ID_CHECK       1086
#define IDC_BUTTON_TRAFFIC_TOTAL        1086
#define IDC_BUTTON_CONNECT              1086
#define IDC_BUTTON_TEMPLATE             1086
#define IDC_BUTTON_TORIGHT              1086
#define IDC_BUTTON_SMS_ARCHIVE          1086
#define IDC_BUTTON_PB_SAVE              1086
#define IDC_BUTTON_TOLEFT               1087
#define IDC_BUTTON2                     1087
#define IDC_BUTTON_LAST                 1087
#define IDC_BUTTON_SET_RESET            1087
#define IDC_BUTTON_CUT_SOME             1087
#define IDC_BUTTON_DELETECONN           1087
#define IDC_BUTTON_RL                   1087
#define IDC_BUTTON_SETUP_POWERMNG_POWEROFF 1087
#define IDC_BUTTON_PVIEW                1087
#define IDC_BUTTON_SETUP_SETCONNPOINT_SET 1087
#define IDC_BUTTON_SETUP_NWSEL_MANUSEL  1087
#define IDC_BUTTON_SETUP_NWSEL_SELECT   1087
#define IDC_BUTTON_MAILTO               1087
#define IDC_BUTTON_PREFER_SMSSOUND_PLAY 1087
#define IDC_BUTTON_USAGE                1087
#define IDC_BUTTON_PB_DELETE            1087
#define IDC_BUTTON_SMS_RESUME           1087
#define IDC_STATIC_NAME                 1088
#define IDC_APN_NAME_EDIT               1088
#define IDC_STATIC_MOBILE               1089
#define IDC_BUTTON_PREV                 1089
#define IDC_BUTTON_AHEAD                1090
#define IDC_STATIC_NUM                  1091
#define IDC_BUTTON_SEARCH               1092
#define IDC_BUTTON_DELETE_ALL           1093
#define IDC_BUTTON_FROM_CSV             1094
#define IDC_BUTTON_IMPORT               1094
#define IDC_STATIC_HOME                 1095
#define IDC_USERNAME_EDIT               1095
#define IDC_STATIC_COMPANY              1096
#define IDC_PASSWORD_EDIT               1096
#define IDC_STATIC_EMAIL                1097
#define IDC_STATIC_MARK                 1098
#define IDC_LIST_PC                     1099
#define IDC_LIST_CARD                   1100
#define IDC_STATIC_TYPE                 1101
#define IDC_PRIMARY_DNS_IPADDRESS       1101
#define IDC_EDIT_PIN_INPUT              1102
#define IDC_SECONDARY_DNS_IPADDRESS     1102
#define IDC_STATIC_PIN_REMAIN           1103
#define IDC_PRIMARY_NBNS_IPADDRESS      1103
#define IDC_STATIC_CONTENT              1104
#define IDC_SECONDARY_NBNS_IPADDRESS    1104
#define IDC_STATIC_URL                  1105
#define IDC_STATIC_TIME                 1106
#define IDC_PS_STATIC                   1106
#define IDC_RADIO_MOBILE                1107
#define IDC_CS_STATIC                   1107
#define IDC_RADIO_HOME                  1108
#define IDC_3GPP_PROFILE_ID_COMBO       1108
#define IDC_RADIO_COMPANY               1109
#define IDC_STATIC_TITLE                1110
#define IDC_PROFILES_LIST               1110
#define IDC_BUTTON_SET_OK               1111
#define IDC_CONFIGURED_PROFILES_GROUP   1111
#define IDC_VIEW_MODIFY_BUTTON          1112
#define IDC_EDIT_SET_NAME               1113
#define IDC_PROFILE_GENERAL_SETTINGS_GROUP 1113
#define IDC_EDIT_SET_LENGTH             1114
#define IDC_PROFILE_NAME_STATIC         1114
#define IDC_STATIC_MAIN                 1115
#define IDC_PROFILE_NAME_EDIT           1115
#define IDC_EDIT_PHONE_NUMBER           1116
#define IDC_PROFILE_PDP_TYPE_STATIC     1116
#define IDC_LIST_MESSAGE                1117
#define IDC_LIST_CALLLOG                1118
#define IDC_PROFILE_PDP_TYPE_COMBO      1118
#define IDC_BUTTON_COPY_ALL             1119
#define IDC_PROFILE_APN_NAME_STATIC     1119
#define IDC_BUTTON_CUT_ALL              1120
#define IDC_PROFILE_APN_NAME_EDIT       1120
#define IDC_BUTTON_COPY_SOME_UP         1121
#define IDC_BUTTON_CUT_SOME_UP          1122
#define IDC_PROFILE_PRIMARY_DNS_IPADDRESS 1122
#define IDC_BUTTON_COPY_ALL_UP          1123
#define IDC_PROFILE_SECONDARY_DNS_STATIC 1123
#define IDC_BUTTON_CUT_ALL_UP           1124
#define IDC_PROFILE_SECONDARY_DNS_IPADDRESS 1124
#define IDC_BUTTON_SAVECONN             1125
#define IDC_PROFILE_USERNAME_STATIC     1125
#define IDC_EDIT_CONN_STATUS            1126
#define IDC_PROFILE_USERNAME_EDIT       1126
#define IDC_PROGRESS_SEND               1127
#define IDC_PROFILE_PASSWORD_STATIC     1127
#define IDC_STATIC_TIP                  1128
#define IDC_PROFILE_PASSWORD_EDIT       1128
#define IDC_BUTTON_HANGUP               1129
#define IDC_BUTTON_REJECT               1129
#define IDC_PROFILE_AUTH_PREF_STATIC    1129
#define IDC_STATIC_SELDIAL              1130
#define IDC_BUTTON_PCANCEL              1130
#define IDC_PROFILE_AUTH_PREF_COMBO     1130
#define IDC_UI_ICON_RSSI                1131
#define IDC_PROFILE_IP_ADDR_STATIC      1131
#define IDC_UI_ICON_SMS_UNRD            1132
#define IDC_PROFILE_IP_ADDR_IPADDRESS   1132
#define IDC_COMBO_SELDOWN               1133
#define IDC_STATIC_NAMEIN               1133
#define IDC_LIST_LEFT                   1133
#define IDC_UI_ICON_NETWK_TYPE          1133
#define IDC_PROFILE_UMTS_REQ_GROUP      1133
#define IDC_STATIC_NUMIN                1134
#define IDC_LIST_RIGHT                  1134
#define IDC_UI_ICON_ROAM                1134
#define IDC_PROFILE_REQ_TRAFFIC_CLASS_STATIC 1134
#define IDC_STATIC_POS                  1135
#define IDC_RADIO1                      1135
#define IDC_UI_ICON_SMS_FULL            1135
#define IDC_RADIO_FILE                  1135
#define IDC_PROFILE_REQ_TRAFFIC_CLASS_COMBO 1135
#define IDC_BUTTON_MODIFY               1136
#define IDC_RADIO2                      1136
#define IDC_STATIC_Set                  1136
#define IDC_UI_ICON_PLMN                1136
#define IDC_PROFILE_REQ_QOS_DELIVERY_ORDER_STATIC 1136
#define IDC_RADIO_OUTLOOK               1136
#define IDC_STATIC_DURATIVETIME_CAPTION 1137
#define IDC_RADIO3                      1137
#define IDC_UI_ICON_HANDSET             1137
#define IDC_PROFILE_REQ_QOS_DELIVERY_ORDER_COMBO 1137
#define IDC_STATIC_SEND_CAPTION         1138
#define IDC_COMBO_LEFT_LOC              1138
#define IDC_RADIO4                      1138
#define IDC_UI_ICON_NWSRV               1138
#define IDC_PROFILE_REQ_MAX_UPLINK_BITRATE_STATIC 1138
#define IDC_STATIC_USER                 1139
#define IDC_COMBO_LEFT_TYPE             1139
#define IDC_PROGRESS1                   1139
#define IDC_UI_ICON_PLMN2               1139
#define IDC_PROFILE_REQ_MAX_UPLINK_BITRATE_EDIT 1139
#define IDC_STATIC_PASSWORD             1140
#define IDC_COMBO_RIGHT_TYPE            1140
#define IDC_STATIC_SCREENINFO           1140
#define IDC_PROFILE_REQ_MAX_DOWNLINK_BITRATE_STATIC 1140
#define IDC_UI_ICON_UPSPEEDICON         1140
#define IDC_STATIC_NUMBER               1141
#define IDC_COMBO_RIGHT_LOC             1141
#define IDC_EDIT_CALLLOG_DATAOUT        1141
#define IDC_PROFILE_REQ_MAX_DOWNLINK_BITRATE_EDIT 1141
#define IDC_STATIC_DURATIVETIME_CAPTION2 1142
#define IDC_EDIT_CALLLOG_COST           1142
#define IDC_PROGRESS                    1142
#define IDC_PROFILE_REQ_GTD_UPLINK_BITRATE_EDIT 1142
#define IDC_CHECK_FLASHMAINDLG          1143
#define IDC_EDIT_CALLLOG_DATAIN         1143
#define IDC_PROGRESS_WAIT               1143
#define IDC_PROFILE_REQ_GTD_UPLINK_BITRATE_STATIC 1143
#define IDC_TAB_SMS                     1144
#define IDC_STATIC_PROMPT               1144
#define IDC_TAB_SETUP                   1144
#define IDC_EDIT_CALLLOG_DURATION       1144
#define IDC_PROFILE_REQ_GTD_DOWNLINK_BITRATE_STATIC 1144
#define IDC_BUTTON_CLEAR                1145
#define IDC_RADIO_SETUP_SKIN_DEFAULT    1145
#define IDC_EDIT_CALLLOG_DATAINOUT      1145
#define IDC_PROFILE_REQ_GTD_DOWNLINK_BITRATE_EDIT 1145
#define IDC_BUTTON_GETPHBITEM           1146
#define IDC_RADIO_SETUP_SKIN_XP         1146
#define IDC_EDIT_CALLLOG_GPRSDURATION   1146
#define IDC_PROFILE_REQ_MAX_SDU_SIZE_STATIC 1146
#define IDC_STATIC_TEXT                 1147
#define IDC_EDIT_CALLLOG_GPRSDATAINOUT  1147
#define IDC_PROFILE_REQ_MAX_SDU_SIZE_EDIT 1147
#define IDC_EDIT_INTERNET_NEWCONN_CONNNAME 1148
#define IDC_EDIT_CALLLOG_UMTSDURATION   1148
#define IDC_PROFILE_REQ_SDU_ERROR_RATIO_STATIC 1148
#define IDC_EDIT_SETUP_SKIN_SKINFILE    1149
#define IDC_EDIT_CALLLOG_UMTSDATAINOUT  1149
#define IDC_PROFILE_REQ_SDU_ERROR_RATIO_COMBO 1149
#define IDC_LIST_SETUP_GENERAL_CONNLIST 1150
#define IDC_PROFILE_REQ_RESIDUAL_BER_RATIO_STATIC 1150
#define IDC_PROFILE_REQ_RESIDUAL_BER_RATIO_COMBO 1151
#define IDC_PROFILE_REQ_ERRONEOUS_SDU_STATIC 1152
#define IDC_PROFILE_REQ_ERRONEOUS_SDU_COMBO 1153
#define IDC_ITEM                        1154
#define IDC_PROFILE_REQ_TRANSFER_DELAY_STATIC 1154
#define IDC_PROFILE_REQ_TRANSFER_DELAY_EDIT 1155
#define IDC_PROFILE_REQ_HANDLING_PRIORITY_STATIC 1156
#define IDC_PIC_DOWN                    1157
#define IDC_PROFILE_REQ_HANDLING_PRIORITY_EDIT 1157
#define IDC_PIC_UP                      1158
#define IDC_PROFILE_UMTS_MIN_GROUP      1158
#define IDC_EDIT_MOBILE                 1159
#define IDC_EDIT_INTERNET_NEWCONN_PHONENUMBER 1159
#define IDC_PROFILE_MIN_TRAFFIC_CLASS_STATIC 1159
#define IDC_EDIT_HOME                   1160
#define IDC_EDIT_INTERNET_NEWCONN_USERNAME 1160
#define IDC_PROFILE_MIN_TRAFFIC_CLASS_COMBO 1160
#define IDC_EDIT_COMPANY                1161
#define IDC_EDIT_INTERNET_NEWCONN_PASSWORD 1161
#define IDC_PROFILE_MIN_QOS_DELIVERY_ORDER_STATIC 1161
#define IDC_EDIT_EMAIL                  1162
#define IDC_STATIC_TIPINFO              1162
#define IDC_EDIT_INTERNET_NEWCONN_APN   1162
#define IDC_PROFILE_MIN_QOS_DELIVERY_ORDER_COMBO 1162
#define IDC_EDIT_MARK                   1163
#define IDC_STATIC_SIGNIN_TIP           1163
#define IDC_PROFILE_MIN_MAX_UPLINK_BITRATE_STATIC 1163
#define IDC_BUTTON_MODIFYPIN            1164
#define IDC_EDIT_SIGNIN_KEY             1164
#define IDC_PROFILE_MIN_MAX_UPLINK_BITRATE_EDIT 1164
#define IDC_BUTTON_UNLOCKPIN            1165
#define IDC_STATIC_PIN_CLCKTIP          1165
#define IDC_PROFILE_MIN_MAX_DOWNLINK_BITRATE_STATIC 1165
#define IDC_STATIC_MPIN_REMAIN          1166
#define IDC_PROFILE_MIN_MAX_DOWNLINK_BITRATE_EDIT 1166
#define IDC_STATIC_MSGBOX_INFO          1167
#define IDC_PROFILE_MIN_GTD_UPLINK_BITRATE_STATIC 1167
#define IDC_STATIC_PINPUK_TITLE         1168
#define IDC_PROFILE_MIN_GTD_UPLINK_BITRATE_EDIT 1168
#define IDC_STATIC_PUK_LOCKTIP          1169
#define IDC_PROFILE_MIN_GTD_DOWNLINK_BITRATE_STATIC 1169
#define IDC_EDIT_SMS_NUM                1170
#define IDC_BTN_OK                      1170
#define IDC_PROFILE_MIN_GTD_DOWNLINK_BITRATE_EDIT 1170
#define IDC_EDIT_SMS_DATETIME           1171
#define IDC_BTN_CANCEL                  1171
#define IDC_PROFILE_MIN_MAX_SDU_SIZE_STATIC 1171
#define IDC_STATIC_SMS_BYTECOUNT        1172
#define IDC_PROFILE_MIN_MAX_SDU_SIZE_EDIT 1172
#define IDC_BUTTON_SMS_PB               1173
#define IDC_STATIC_LEAVETIME            1173
#define IDC_PROFILE_MIN_SDU_ERROR_RATIO_STATIC 1173
#define IDC_BUTTON_SMS_CLEAR            1174
#define IDC_PROFILE_MIN_SDU_ERROR_RATIO_COMBO 1174
#define IDC_BUTTON_SMS_PB2              1175
#define IDC_PROFILE_MIN_RESIDUAL_BER_RATIO_STATIC 1175
#define IDC_LIST_SETUP_NWSEL_NWLIST     1176
#define IDC_PROFILE_MIN_RESIDUAL_BER_RATIO_COMBO 1176
#define IDC_BUTTON_SETUP_NWSEL_SET      1177
#define IDC_PROFILE_MIN_ERRONEOUS_SDU_STATIC 1177
#define IDC_EDIT_PRE_MSG                1178
#define IDC_PROFILE_MIN_ERRONEOUS_SDU_COMBO 1178
#define IDC_EDIT_jfkd                   1179
#define IDC_STATIC_VERSION              1179
#define IDC_PROFILE_MIN_TRANSFER_DELAY_STATIC 1179
#define IDC_LANGUAGE1                   1180
#define IDC_PROFILE_MIN_TRANSFER_DELAY_EDIT 1180
#define IDC_LANGUAGE2                   1181
#define IDC_PROFILE_MIN_HANDLING_PRIORITY_STATIC 1181
#define IDC_COPYRIGHT                   1182
#define IDC_PROFILE_MIN_HANDLING_PRIORITY_EDIT 1182
#define IDC_RICHEDIT1                   1183
#define IDC_PROFILE_GPRS_REQ_GROUP      1183
#define IDC_BUTTON_SETUP_SCA_GET        1184
#define IDC_PROFILE_REQ_PRECEDENCE_CLASS_STATIC 1184
#define IDC_BUTTON_SETUP_SCA_SET        1185
#define IDC_PROFILE_REQ_PRECEDENCE_CLASS_COMBO 1185
#define IDC_RADIO_SETUP_NWSEL_AUTOSEL   1186
#define IDC_PROFILE_REQ_DELAY_CLASS_STATIC 1186
#define IDC_RADIO_SETUP_NWSEL_MANSEL    1187
#define IDC_PROFILE_REQ_DELAY_CLASS_COMBO 1187
#define IDC_RADIO_SETUP_NWSEL_UMTSONLY  1188
#define IDC_PROFILE_REQ_RELIABILITY_CLASS_STATIC 1188
#define IDC_RADIO_SETUP_NWSEL_GEONLY    1189
#define IDC_PROFILE_REQ_RELIABILITY_CLASS_COMBO 1189
#define IDC_RADIO_SETUP_NWSEL_UMTSPRE   1190
#define IDC_PROFILE_REQ_PEAK_THRU_CLASS_STATIC 1190
#define IDC_RADIO_SETUP_NWSEL_GEPRE     1191
#define IDC_PROFILE_REQ_PEAK_THRU_CLASS_COMBO 1191
#define IDC_PROFILE_REQ_MEAN_THRU_CLASS_STATIC 1192
#define IDC_PROFILE_REQ_MEAN_THRU_CLASS_COMBO 1193
#define IDC_PROFILE_GPRS_MIN_GROUP      1194
#define IDC_PROFILE_MIN_PRECEDENCE_CLASS_STATIC 1195
#define IDC_STATIC_MODEPRE              1196
#define IDC_PROFILE_MIN_PRECEDENCE_CLASS_COMBO 1196
#define IDC_LIST_LANGLIST               1197
#define IDC_PROFILE_MIN_DELAY_CLASS_STATIC 1197
#define IDC_STA_APPNAME                 1198
#define IDC_PROFILE_MIN_DELAY_CLASS_COMBO 1198
#define IDC_STATIC_MSG                  1199
#define IDC_PROFILE_MIN_RELIABILITY_CLASS_STATIC 1199
#define ID_SEND                         1200
#define IDC_PROFILE_MIN_RELIABILITY_CLASS_COMBO 1200
#define IDC_CONTACT_PIC                 1201
#define IDC_LIST_EXTRACT_NUM            1201
#define IDC_STATIC_SEGE                 1201
#define ID_EXIT                         1201
#define IDC_PROFILE_MIN_PEAK_THRU_CLASS_STATIC 1201
#define IDC_COMBO_VALPERIOD             1202
#define IDC_STATIC_ANSWER_1             1202
#define IDC_PROFILE_MIN_PEAK_THRU_CLASS_COMBO 1202
#define IDC_COMBO_DELIREPORT            1203
#define IDC_STATIC_SEND_1               1203
#define IDC_PROFILE_MIN_MEAN_THRU_CLASS_STATIC 1203
#define IDC_COMBO_MSGSAVEPLACE          1204
#define IDC_COMBO_PREFSTOR              1204
#define IDC_CHECK_PREFER_CONNNET        1204
#define IDC_COMBO_SELLOC                1204
#define IDC_PROFILE_MIN_MEAN_THRU_CLASS_COMBO 1204
#define IDC_CONTACT_PICS                1205
#define IDC_CHECK_PREFER_STARTMINI      1205
#define IDC_CREATE_BUTTON               1205
#define IDC_COMBO_LOC_FILTER            1206
#define IDC_CHECK_PREFER_ALERTWINDOW    1206
#define IDC_STATIC_INT_TIP              1206
#define IDC_DELETE_BUTTON               1206
#define IDC_UI_ICON_UPSPEED             1207
#define IDC_CHECK_PREFER_ALERTTONE      1207
#define IDC_UI_ICON_DWSPEED             1208
#define IDC_BUTTON_PREFER_USAGELIMIT    1208
#define IDC_RADIO_CHAP                  1208
#define IDC_RADIO_PAP                   1209
#define IDC_UI_ICON_UPFLUX              1209
#define IDC_BUTTON_PREFER_DIAGNOSTICS   1209
#define IDC_UI_ICON_DWFLUX              1210
#define IDC_BUTTON_PREFER_DEFAULT       1210
#define IDC_CHECK_PREFER_LAUNCHAPP      1211
#define IDC_RADIO_PREFER_SLEEP_PREVENT  1212
#define IDC_SIM_ACTION_COMBO            1212
#define IDC_RADIO_PREFER_SLEEP_ALLOW    1213
#define IDC_PIN_ID_COMBO                1213
#define IDC_BUTTON_PREFER_CANCEL        1214
#define IDC_STATIC_DIAG_SMS_NUM         1215
#define IDC_SIM_SUBMIT_BUTTON           1215
#define IDC_STATIC_DIAG_PBM_NUM         1216
#define IDC_SIM_FIELD1_EDIT             1216
#define IDC_STATIC_DIAG_IMEI_NUM        1217
#define IDC_SIM_FIELD2_EDIT             1217
#define IDC_STATIC_DIAG_SOFT_VER        1218
#define IDC_PIN1_STATUS_STATIC          1218
#define IDC_STATIC_DIAG_FIRM_VER        1219
#define IDC_PIN2_STATUS_STATIC          1219
#define IDC_PIN1_VERIFY_STATIC          1220
#define IDC_PIN1_UNBLOCK_STATIC         1221
#define IDC_PINI2_VERIFY_STATIC         1222
#define IDC_PIN2_UNBLOCK_STATIC         1223
#define IDC_PIN1_GROUP_STATIC           1224
#define IDC_CHECK_INT_USAGE_PROMPT      1225
#define IDC_PIN2_GROUP_STATIC           1225
#define IDC_CHECK_INT_USAGE_DISCONN     1226
#define IDC_SIM_ACTIONS_GROUP_STATIC    1226
#define IDC_CHECK_INT_USAGE_PWD         1227
#define IDC_STATIC1                     1227
#define IDC_SIM_ACTION_STATIC           1227
#define IDC_STATIC_FREENUM              1228
#define IDC_PIN_ID_STATIC               1228
#define IDC_RADIO_NDIS                  1229
#define IDC_SIM_FIELD1_STATIC           1229
#define IDC_STATIC_SMS                  1229
#define IDC_RADIO_RAS                   1230
#define IDC_SIM_FIELD2_STATIC           1230
#define IDC_TREE_PHONEBOOK              1230
#define IDC_TREE_SMS                    1230
#define IDC_BUTTON_NET_STATISTICS       1232
#define IDC_TREE_NET                    1234
#define IDC_COMBO_CONNECT_PROFILE       1238
#define IDC_LIST_PBGROUP                1240
#define ID_BUTTON_NEWGP                 1241
#define ID_BUTTON_EDITGP                1242
#define ID_BUTTON_DELETEGP              1243
#define IDC_STATIC_NUMBER3              1244
#define ID_BUTTON_GROUP_OK              1244
#define ID_BUTTON_EDITMEMBER            1245
#define IDC_LIST_GROUPMEMBERS           1246
#define IDC_LIST_GROUPMEMBER            1247
#define IDC_LIST_SMSTEST                1250
#define IDC_COMBO_GROUP                 1251
#define IDC_BUTTON_EXPANDALL            1253
#define IDC_BUTTON_COLLAPSEALL          1254
#define IDC_RADIO_MANUAL                1255
#define IDC_BUTTON_NETLOG               1255
#define IDC_STATIC_SMS_BTN_BKGROUND     1255
#define IDC_RADIO_AUTOMATIC             1256
#define IDC_RADIO_SMS_GENERAL           1257
#define IDC_STATIC_USIM                 1257
#define IDC_STATIC_TABBKGROUD           1257
#define IDC_STATIC_PINSTR               1257
#define IDC_RADIO_SMS_URGENT            1258
#define IDC_RADIO_SMS_EMERGENCY         1259
#define IDC_TEXT_MESSAGE                1259
#define IDC_STATIC_SMS_CENTER           1259
#define IDC_RADIO_SMS_INTERACTIVE       1260
#define IDC_TEXT_CONTACTS               1260
#define IDC_BUTTON_RESETSTATISTICS      1261
#define IDC_COMBO_IMEI                  1262
#define IDC_TEXT_ESN                    1263
#define IDC_COMBO_STORAGETYPE           1264
#define IDC_STORAGETYPE                 1265
#define IDC_STATIC_IMEI                 1266
#define IDC_STA_VOICEMAILNUMBER         1272
#define ID_READCFT_SAVE                 1273
#define IDC_STATIC_SECONDS              1280
#define IDC_BUTTON_NEXT                 1287
#define IDC_STATIC_RadioSet             1288
#define IDC_BTN_PINDISABLE              2088
#define IDC_BTN_PINMODIFY               2089
#define IDC_BTN_PINUNLOCK               2090
#define IDC_BTN_PINENABLE               2093
#define IDC_BUTTON_BTNPROFILES          2900
#define IDC_BUTTON_NWSET                3086
#define IDC_STATIC_INSTRUCTION          3237
#define IDC_TAB_NETWORK_SETTINGS        3252
#define IDC_RADIO_SETUP_NWSEL_GEONLY_MODE 3253
#define IDC_RADIO_SETUP_NWSEL_UMTSONLY_MODE 3254
#define IDC_RADIO_SETUP_NWSEL_GEPRE_MODE 3255
#define IDC_RADIO_SETUP_NWSEL_UMTSPRE_MODE 3256
#define IDC_COMBO_SMS_PRIORITY          3257
#define IDC_RADIO_NWSEL_SEARCH_AUTOSEL  3258
#define IDC_RADIO_NWSEL_SEARCH_MANSEL   3259
#define IDC_EDIT_PREFER_SMSSOUND_FILE_SMSSET 3308
#define IDD_DIALOG_SETUP_NW_MODE        3321
#define IDD_DIALOG_SETUP_NW_SEARCH      3323
#define IDB_BITMAP_STATUSICON_BKGROUND  3326
#define IDS_SETUPNWSEL_TAB_MODE         3330
#define IDC_LIST_NWSEL_SEARCH_NWLIST    3350
#define IDC_TAB_CALLHISTORY_CALL        3360
#define IDC_LIST_CALLHISTORY_CALL       3362
#define IDC_CHECK_PREFER_ALERTWINDOWS_SMSSET 3363
#define IDC_CHECK_PREFER_ALERTTONE_SMSSET 3364
#define IDC_BUTTON_NWSEL_SEARCH_REFRESH 3386
#define IDC_BUTTON_NWSEL_SEARCH_SELECT  3387
#define IDC_BUTTON_PREFER_SMSSOUND_BROWSE_SMSSET 3388
#define IDC_BUTTON_PREFER_SMSSOUND_PLAY_SMSSET 3389
#define IDS_SMS_SEARCH                  3399
#define IDS_TREE_TRANSFER               3400
#define IDS_TREE_TRANSFERTIME           3401
#define IDS_TREE_UPLOAD                 3402
#define IDS_TREE_DOWNLOAD               3403
#define IDS_TREE_DATA                   3404
#define IDS_TREE_SPEED                  3405
#define IDS_TREE_UPLOADED_DATA          3406
#define IDS_TREE_DOWNLOADED_DATA        3407
#define IDS_TREE_STATISTICS             3408
#define IDS_TREE_DAILY                  3409
#define IDS_TREE_MONTHLY                3410
#define IDS_TREE_YEARLY                 3411
#define IDS_NETTREE_NETLOG              3412
#define IDS_STATIC_USIM                 3413
#define IDS_STATIC_RUIM                 3414
#define IDS_WARNING_INPUTGROUP          3415
#define IDS_WARNING_GROUPEXISTED        3416
#define IDS_DEFAULT                     3417
#define IDS_SMSTREE_ARCHIVE             3418
#define IDS_SMSTREE_LOCAL               3419
#define IDS_SMSTREE_USIM                3420
#define IDS_SMSTREE_INBOX               3421
#define IDS_SMSTREE_OUTBOX              3422
#define IDS_SMSTREE_DRAFT               3423
#define IDS_SMS_ARCHIVE                 3424
#define IDS_SMS_ARCHIVESUCC             3425
#define IDS_SMS_ARCHIVEFAIL             3426
#define IDS_SMS_RESUMESUCC              3427
#define IDS_SMS_RESUMEFAIL              3428
#define IDS_SMS_RESUME                  3429
#define IDS_SMSTREE_USBMODEM            3430
#define IDC_EDIT_SMS_SEARCH             3464
#define IDC_BUTTON_SMS_SEARCH           3486
#define IDC_STATIC_PRIORITY             4258
#define IDC_STATIC_DEFDELIVERY          4260
#define IDC_COMBO_DEFDELIVERY           4261
#define IDS_MESSAGE_USBMODEM            5418
#define IDS_MESSAGE_RUIM                5419
#define IDS_MESSAGE_USIM                5420
#define IDS_ESN                         5421
#define IDS_CONTACTS_USBMODEM           5422
#define IDS_CONTACTS_USIM               5423
#define IDS_CONTACTS_RUIM               5424
#define IDS_SMS_SETSUCC                 5425
#define IDS_SETSMSW_6HOUR               5427
#define IDS_SETSMSW_1DAY                5428
#define IDS_SETSMSW_3DAY                5429
#define IDS_SETSMSW_1WEEK               5430
#define IDS_SETSMSW_MAX                 5431
#define IDS_SETSMSC_30MIN               5432
#define IDS_SETSMSC_1HOUR               5433
#define IDS_SETSMSC_2HOUR               5434
#define IDS_SETSMSC_6HOUR               5435
#define IDS_SETSMSC_12HOUR              5436
#define IDS_SETSMSC_1DAY                5437
#define IDS_SETSMSC_1WEEK               5438
#define IDS_SETSMSC_MAX                 5439
#define IDS_SETSMSC_DEFAULT             5440
#define IDS_SETSMSW_1HOUR               15426
#define IDS_NAMEANDNUMBER               15427
#define IDS_USAGE                       15428
#define IDS_OPTIONS                     15429
#define IDS_CONNECTION                  15430
#define IDS_CALLTIP                     15431
#define IDS_SMSTIP                      15432
#define IDS_PHONEBOOKTIP                15433
#define IDS_SETUP_SMS_PRI1              15434
#define IDS_SETUP_SMS_PRI2              15435
#define IDS_SETUP_SMS_PRI3              15436
#define IDS_SETUP_SMS_PRI4              15437
#define IDC_EDIT_CFTSMS_CONTENT         22008
#define IDC_EDIT_CFTSMS_NUM             22009
#define IDC_EDIT_CFTSMS_DATETIME        22010
#define IDC_EDIT_CFTSMS_NAME            22064
#define IDC_STATIC_CFTNAME              22273
#define IDC_STATIC_CFTNUMBER            22274
#define IDC_STATIC_CFTTIME              22275
#define IDC_STATIC_CFTCONTENT           22276
#define IDC_STATIC_CFTSMS_BYTECOUNT     22277
#define IDS_STR_WRITESMS_TITILE         25438
#define IDS_STR_INVALID_USERNAMEPWD     25439
#define IDS_STR_CONNECTION_ERROR        25440
#define IDS_STR_VOICEMAIL               25444
#define IDS_STR_VOICELISTEN             25445
#define ID_ITEM_1                       32771
#define ID_APP_OPEN                     32771
#define ID_MHIST_RECALL                 32771
#define ID_ITEM_2                       32772
#define ID_MHIST_ABSTRACT               32772
#define ID_ITEM_3                       32773
#define ID_ITEM1                        32773
#define ID_MHIST_SENDSMS                32773
#define ID_ITEM_4                       32774
#define ID_ITEM2                        32774
#define ID_MHIST_DELETE                 32774
#define ID_DIALOG_ABOUT                 32775
#define ID_ITEM3                        32775
#define ID_MHIST_DELETEALL              32775
#define ID_ITEM4                        32776
#define ID_MLOG_DELETE                  32776
#define ID_MLOG_DELETEALL               32777
#define ID_MLOG_EXPORT                  32778
#define ID_APP_TRAY_MAXI                32779
#define IDS_STR_LASTVOICEMAIL           35441
#define IDS_STR_CLEAR_VMAILICON         35442
#define IDC_UI_ICON_VOICESMS            51271

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        296
#define _APS_NEXT_COMMAND_VALUE         32780
#define _APS_NEXT_CONTROL_VALUE         1200
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
